//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoYqlp.WepApp.Infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoYDBConnection : DbContext
    {
        public CoYDBConnection()
            : base("name=CoYDBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoY_Roles> CoY_Roles { get; set; }
        public virtual DbSet<CoY_UserClaims> CoY_UserClaims { get; set; }
        public virtual DbSet<CoY_UserLogins> CoY_UserLogins { get; set; }
        public virtual DbSet<CoY_UserRoles> CoY_UserRoles { get; set; }
        public virtual DbSet<CoY_Users> CoY_Users { get; set; }
        public virtual DbSet<SYSLog> SYSLogs { get; set; }
    }
}
