//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoYqlp.WepApp.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string LogMessage { get; set; }
        public string LogExeption { get; set; }
        public string StackTrace { get; set; }
        public string Provider { get; set; }
        public string TargetName { get; set; }
        public string UserID { get; set; }
        public string Location { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
